### ISSUE TITLE
training and testing

### ISSUE THREAD

**Issue by ghost** [zhengziqiang/ReshapeGAN#1]
any update on training and testing code?

**Comment by zhengziqiang** [comment]
The codes will come soon. Now I am busy for writing my nips paper. I will upload the codes after 23, May.

**Comment by ghost** [comment]
ok thanks, looking forward to try out the code and pretrained models, good luck on your nips paper

**Comment by ghost** [comment]
@zhengziqiang does this work without a facial attribute txt file?

**Comment by zhengziqiang** [comment]
Only for the first setting, we use the facial attribute txt file, and for the other settings, we use the landmark or skeleton information.

**Comment by ghost** [comment]
@zhengziqiang ok, seems similar to stargan then for facial attributes, any update on the committing the code?

**Comment by ghost** [comment]
@zhengziqiang just wondering if there are any updates thanks :)
